
name: Minify JavaScript Files

on:
  push: 
    branches:
      - main
    paths:
      - '**/*.js'
      - '! **/*.min.js'

jobs:
  minify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses:  actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '18'

      - name: Install Terser
        run: npm install -g terser

      - name:  Minify _shared/licensing.js
        run: |
          if [ -f "_shared/licensing. js" ]; then
            terser _shared/licensing.js \
              --compress \
              --mangle \
              --comments "/^! /" \
              --output _shared/licensing.min.js
            echo "✅ Minified _shared/licensing.js"
          fi

      - name:  Minify all plugin files
        run: |
          for plugin in */; do
            if [ -f "${plugin}${plugin%/}. js" ] && [ "${plugin}" != "node_modules/" ] && [ "${plugin}" != "_shared/" ] && [ "${plugin}" != "scripts/" ] && [ "${plugin}" != ". github/" ]; then
              terser "${plugin}${plugin%/}.js" \
                --compress \
                --mangle \
                --comments "/^!/" \
                --output "${plugin}${plugin%/}.min.js"
              echo "✅ Minified ${plugin%/}"
            fi
          done

      - name:  Commit minified files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add **/*.min.js
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-minify JavaScript files"
            git push
          fi
